#pragma once
#include <SFML/Window.hpp>
#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <iostream>
#include <fstream>
#include <string>
#include "../Music/Sound.h"
#include "Movement.h"
#include "../Levels/Levels.h"
#include "../Menu/Inventory.h"
#include "../Enemy/Enemy.h"
#include "../Memories/Memories.h"
#include "Text.h"
#include "../Menu/Menu.h"
